services:
  - type: web
    name: aws-bulk-mailer-backend
    runtime: node
    repo: https://github.com/lodhikmjb/my-aws-mailer
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node aws-mailer.cjs
    envVars:
      - key: PORT
        value: 5001
